fos_rest:
    body_converter:
        enabled: true
    param_fetcher_listener: force
#    body_listener:
#        array_normalizer: fos_rest.normalizer.camel_keys
    format_listener:
        enabled: true
        rules:
            - { path: '^/', priorities: ['json', 'html'], fallback_format: 'html' }
    routing_loader:
        default_format: json
        include_format: false
    service:
        serializer: "fos_rest.serializer.jms"

